---
Name: flickrtestroutes
After:
  - '#rootroutes'
  - '#coreroutes'
---

SilverStripe\Control\Director:
  rules:
    'flickrexport': 'Suilven\Flickr\Controller\FlickrExportController'
    'flickr': 'Suilven\Flickr\Controller\FlickrController'
